#!/bin/bash
# Ensures that leaving both options empty makes no change to apt sources, on every base image the
# autogenerated suite runs against: the defaults must be safe to apply anywhere.
set -e

# shellcheck source=/dev/null
source 'dev-container-features-test-lib'

# os-release(5) allows quoted values, so ID="ubuntu" has to be recognized here too.
# shellcheck source=/dev/null
if (. '/etc/os-release' && [ "${ID:-}" = 'ubuntu' ]); then
  # ports.ubuntu.com is what the arm64 images name instead.
  check 'apt sources still reference the default Ubuntu hosts' bash -c \
    'grep -qrE "https?://((archive|security)\.ubuntu\.com/ubuntu|ports\.ubuntu\.com/ubuntu-ports)" /etc/apt/sources.list.d/'
else
  check 'apt sources still reference the default Debian archive' bash -c \
    'grep -qE "https?://deb\.debian\.org/debian/?$" /etc/apt/sources.list.d/debian.sources'
  check 'apt sources still reference the default Debian security archive' bash -c \
    'grep -qE "https?://deb\.debian\.org/debian-security/?$" /etc/apt/sources.list.d/debian.sources'
fi

check 'apt sources are still parseable' apt-get indextargets

reportResults
