#!/bin/bash
# Ensures that leaving the mirror option empty makes no change to apt sources, on any base image
# the autogenerated suite runs against -- including the non-Ubuntu ones the feature refuses.
set -e

# shellcheck source=/dev/null
source dev-container-features-test-lib

if grep -qE '^ID=ubuntu$' /etc/os-release; then
  check "apt sources still reference the default Ubuntu archive host" bash -c \
    "grep -qrE 'https?://(archive|security)\.ubuntu\.com' /etc/apt/sources.list /etc/apt/sources.list.d/ 2>/dev/null"
else
  check "apt sources of a non-Ubuntu image are left alone" bash -c \
    "! grep -qrE 'https?://(archive|security)\.ubuntu\.com' /etc/apt/sources.list /etc/apt/sources.list.d/ 2>/dev/null"
fi

check "no backup files are left behind" bash -c \
  "! ls /etc/apt/sources.list.apt-mirror.bak /etc/apt/sources.list.d/*.apt-mirror.bak >/dev/null 2>&1"
check "apt sources are still parseable" apt-get indextargets

reportResults
